### ISSUE TITLE
app / webview 폴더 구조에 맞게 세팅

### ISSUE THREAD

**Issue by yoon-junseo** [daehwahap/monorepo#24]
## 설명
- app과 webview에 폴더 구조에 맞게 lint import / tsconfig의 alias 설정 추가
```
- assets
- components
- features -> 화면 단위로
   - 화면
      - components
      - constants.ts
      - hooks.ts
      - store.ts
      - utils.ts
- shared -> 공용 / 전역
   - constants
   - hooks
   - store
   - utils
   - types
- screens -> react-native
- navigators -> react-native / Tab.Navigator, Stack.Navigator 모음
- app -> next.js
```

## TODO

- [x] app의 lint import
- [x] app의 tsconfig의 alias 설정
- [x] webview의 lint import
- [x] webview의 tsconfig의 alias 설정
