### ISSUE TITLE
[app][webview] suspense / error boundary 설정

### ISSUE THREAD

**Issue by yoon-junseo** [daehwahap/monorepo#33]
## 설명
- app과 webview에서 사용할 기본적인 suspense / error boundary 설정

## TODO

- [x] packages/shared에 error boundary 추가
- [x] trpc suspense / error boundary 테스트
- [x] app router에서 suspense 테스트
